plant=[{
      "plantNo":1,
      "plantName":"페튜니아",
      "plantScientific":"Petunia",
      "plantOrigin":"남아메리카",
      "plantFamily":"가지과",
      "plantGroup":"씨앗주머니L",
      "plantLuminous":"양지",
      "plantWatering":"비교적 건조해도 잘 자란다.",
      "plantPoint":100
   },
   {
      "plantNo":2,
      "plantName":"보스톤",
      "plantScientific":"Nephrolepis exaltata",
      "plantOrigin":"열대원산종의 원예품종",
      "plantFamily":"고사리과",
      "plantGroup":"씨앗주머니D",
      "plantLuminous":"양지",
      "plantWatering":"물이 마르지 않도록 관리",
      "plantPoint":60
   },
   {
      "plantNo":3,
      "plantName":"마거리트",
      "plantScientific":"Argyranthemum frutescens",
      "plantOrigin":"아프리카 카나리아섬",
      "plantFamily":"국화과",
      "plantGroup":"씨앗주머니A",
      "plantLuminous":"양지",
      "plantWatering":"배수가 좋은 상태에서 충분히 물주기",
      "plantPoint":20
   },
   {
      "plantNo":4,
      "plantName":"익소라",
      "plantScientific":"Ixora",
      "plantOrigin":"인도, 중국, 말레이시아",
      "plantFamily":"꼭두서니과",
      "plantGroup":"씨앗주머니A",
      "plantLuminous":"음지",
      "plantWatering":"따듯한 물로 흙이 마르지 않도록 관리",
      "plantPoint":20
   },
   {
      "plantNo":5,
      "plantName":"케이프담쟁이",
      "plantScientific":"Senecio mikanioides",
      "plantOrigin":"남아프리카 공화국",
      "plantFamily":"국화과",
      "plantGroup":"씨앗주머니A",
      "plantLuminous":"음지",
      "plantWatering":"겉흙이 말랐을 때 한 번 흠뻑 물주기",
      "plantPoint":20
   },
   {
      "plantNo":6,
      "plantName":"스테비아",
      "plantScientific":"Stevia rebaudiana",
      "plantOrigin":"파라과이, 아르헨티나, 브라질, 등",
      "plantFamily":"국화과",
      "plantGroup":"씨앗주머니A",
      "plantLuminous":"양지",
      "plantWatering":"흙이 거의 마를 때 쯤 물주기",
      "plantPoint":20
   },
   {
      "plantNo":7,
      "plantName":"펜타스",
      "plantScientific":"Pentas",
      "plantOrigin":"남부 아프리카, 코모로, 마다가스카르 등",
      "plantFamily":"꼭두서니과",
      "plantGroup":"씨앗주머니A",
      "plantLuminous":"양지",
      "plantWatering":"물은 충분히 주되 물빠짐이 좋아야함",
      "plantPoint":20
   },
   {
      "plantNo":8,
      "plantName":"레몬밤",
      "plantScientific":"Melissa officinalis",
      "plantOrigin":"지중해",
      "plantFamily":"꿀풀과",
      "plantGroup":"씨앗주머니B",
      "plantLuminous":"음지",
      "plantWatering":"윗 흙이 살짝 마를 때 뿌리 깊숙히까지 물주기",
      "plantPoint":30
   },
   {
      "plantNo":9,
      "plantName":"로즈마리",
      "plantScientific":"Salvia rosmarinus",
      "plantOrigin":"지중해",
      "plantFamily":"꿀풀과",
      "plantGroup":"씨앗주머니B",
      "plantLuminous":"음지",
      "plantWatering":"1~2주일 간격으로 물주기",
      "plantPoint":30
   },
   {
      "plantNo":10,
      "plantName":"마조람",
      "plantScientific":"Origanum majorana",
      "plantOrigin":"지중해",
      "plantFamily":"꿀풀과",
      "plantGroup":"씨앗주머니B",
      "plantLuminous":"양지",
      "plantWatering":"규칙적으로 과하지 않게 물주기",
      "plantPoint":30
   },
   {
      "plantNo":11,
      "plantName":"바질",
      "plantScientific":"Ocimum basilicum",
      "plantOrigin":"열대 아시아",
      "plantFamily":"꿀풀과",
      "plantGroup":"씨앗주머니B",
      "plantLuminous":"양지",
      "plantWatering":"1주일 마다 1인치 정도의 물주기",
      "plantPoint":30
   },
   {
      "plantNo":12,
      "plantName":"백리향",
      "plantScientific":"Thymus",
      "plantOrigin":"한국",
      "plantFamily":"꿀풀과",
      "plantGroup":"씨앗주머니B",
      "plantLuminous":"양지",
      "plantWatering":"겉흙이 마르면 물을 충분히 준다 ",
      "plantPoint":30
   },
   {
      "plantNo":13,
      "plantName":"스피아민트",
      "plantScientific":"Mentha spicata",
      "plantOrigin":"유럽, 아시아 ",
      "plantFamily":"꿀풀과",
      "plantGroup":"씨앗주머니B",
      "plantLuminous":"양지",
      "plantWatering":"물이 마르지 않도록 관리",
      "plantPoint":30
   },
   {
      "plantNo":14,
      "plantName":"애플민트",
      "plantScientific":"Mentha suaveolens",
      "plantOrigin":"유럽",
      "plantFamily":"꿀풀과",
      "plantGroup":"씨앗주머니B",
      "plantLuminous":"음지",
      "plantWatering":"1~2인치의 물을 1주일 마다 주기",
      "plantPoint":30
   },
   {
      "plantNo":15,
      "plantName":"오레가노",
      "plantScientific":"Origanum vulgare",
      "plantOrigin":"유럽, 서남아시아",
      "plantFamily":"꿀풀과",
      "plantGroup":"씨앗주머니B",
      "plantLuminous":"양지",
      "plantWatering":"물이 마르지 않도록 관리",
      "plantPoint":30
   },
   {
      "plantNo":16,
      "plantName":"오렌지타임",
      "plantScientific":"Thymus Orange Balsam",
      "plantOrigin":"지중해",
      "plantFamily":"꿀풀과",
      "plantGroup":"씨앗주머니B",
      "plantLuminous":"양지",
      "plantWatering":"굉장히 건조한 환경에서만 물주기",
      "plantPoint":30
   },
   {
      "plantNo":17,
      "plantName":"체리세이지",
      "plantScientific":"Salvia micrphylla",
      "plantOrigin":"유럽, 미국",
      "plantFamily":"꿀풀과",
      "plantGroup":"씨앗주머니B",
      "plantLuminous":"양지",
      "plantWatering":"흙이 마르지 않도록 1주일에 1~2번 정도 물주기",
      "plantPoint":30
   },
   {
      "plantNo":18,
      "plantName":"카펫타임",
      "plantScientific":"Thymus Herbabarona cv.",
      "plantOrigin":"유럽",
      "plantFamily":"꿀풀과",
      "plantGroup":"씨앗주머니B",
      "plantLuminous":"양지",
      "plantWatering":"흙이 완전히 마를 때 한 번 씩 물주기",
      "plantPoint":30
   },
   {
      "plantNo":19,
      "plantName":"크리핑로즈마리",
      "plantScientific":"Rosmarinus officinalis prostratus",
      "plantOrigin":"지중해",
      "plantFamily":"꿀풀과",
      "plantGroup":"씨앗주머니B",
      "plantLuminous":"양지",
      "plantWatering":"물이 마르지 않도록 관리",
      "plantPoint":30
   },
   {
      "plantNo":20,
      "plantName":"페퍼민트",
      "plantScientific":"Mentha × piperita",
      "plantOrigin":"유럽",
      "plantFamily":"꿀풀과",
      "plantGroup":"씨앗주머니B",
      "plantLuminous":"음지",
      "plantWatering":"물이 마르지 않도록 관리",
      "plantPoint":30
   },
   {
      "plantNo":21,
      "plantName":"프렌치라벤더",
      "plantScientific":"Lavandula stoechas",
      "plantOrigin":"카나리아제도, 스페인, 아프리카북부",
      "plantFamily":"꿀풀과",
      "plantGroup":"씨앗주머니B",
      "plantLuminous":"양지",
      "plantWatering":"심은 첫째 주에 3일에 한 번씩 물주기",
      "plantPoint":30
   },
   {
      "plantNo":22,
      "plantName":"프린지드 라벤더",
      "plantScientific":"Lavandula dentata",
      "plantOrigin":"스페인 남동부",
      "plantFamily":"꿀풀과",
      "plantGroup":"씨앗주머니B",
      "plantLuminous":"양지",
      "plantWatering":"화분의 흙이 마르면 물주기",
      "plantPoint":30
   },
   {
      "plantNo":23,
      "plantName":"핫립세이지",
      "plantScientific":"Salvia microphylla Hot Lips",
      "plantOrigin":"멕시코",
      "plantFamily":"꿀풀과",
      "plantGroup":"씨앗주머니B",
      "plantLuminous":"양지",
      "plantWatering":"물이 마르지 않도록 관리",
      "plantPoint":30
   },
   {
      "plantNo":24,
      "plantName":"넉줄고사리",
      "plantScientific":"Davallia mariesii",
      "plantOrigin":"한국, 중국, 일본, 타이완",
      "plantFamily":"넉줄고사리과",
      "plantGroup":"씨앗주머니D",
      "plantLuminous":"음지",
      "plantWatering":"1주일에 한 두 번씩 흙이 젖을 때 까지 물주기",
      "plantPoint":60
   },
   {
      "plantNo":25,
      "plantName":"줄고사리(더피)",
      "plantScientific":"Nephrolepis cordifolia",
      "plantOrigin":"일본",
      "plantFamily":"넉줄고사리과",
      "plantGroup":"씨앗주머니D",
      "plantLuminous":"음지",
      "plantWatering":"흙이 마르지 않게 물주기",
      "plantPoint":60
   },
   {
      "plantNo":26,
      "plantName":"은사철",
      "plantScientific":"Euonymus japonica 'Albomarginata'",
      "plantOrigin":"한국, 중국, 일본",
      "plantFamily":"노박덩굴과",
      "plantGroup":"씨앗주머니D",
      "plantLuminous":"양지",
      "plantWatering":"1주일에 1,2번씩 물주기",
      "plantPoint":60
   },
   {
      "plantNo":27,
      "plantName":"레몬머틀",
      "plantScientific":"Backhousia citriodora",
      "plantOrigin":"호주",
      "plantFamily":"도금양과",
      "plantGroup":"씨앗주머니A",
      "plantLuminous":"양지",
      "plantWatering":"배수 좋은 상태 필요",
      "plantPoint":20
   },
   {
      "plantNo":28,
      "plantName":"티트리",
      "plantScientific":"Melaleuca alternifolia",
      "plantOrigin":"오스트레일리아",
      "plantFamily":"도금양과",
      "plantGroup":"씨앗주머니A",
      "plantLuminous":"양지",
      "plantWatering":"1주일에 한 번씩 흙의 2인치 정도가 젖을 만큼 물주기",
      "plantPoint":20
   },
   {
      "plantNo":29,
      "plantName":"염자",
      "plantScientific":"Crassula ovata",
      "plantOrigin":"남아프리카, 모잠비크",
      "plantFamily":"돌나무과",
      "plantGroup":"씨앗주머니H",
      "plantLuminous":"양지",
      "plantWatering":"2~3주에 한 번씩 물주기",
      "plantPoint":80
   },
   {
      "plantNo":30,
      "plantName":"청법사",
      "plantScientific":"Aeonium arboreum",
      "plantOrigin":"카나리아 제도",
      "plantFamily":"돌나무과",
      "plantGroup":"씨앗주머니H",
      "plantLuminous":"양지",
      "plantWatering":"흙이 건조할 때 물주기",
      "plantPoint":80
   },
   {
      "plantNo":31,
      "plantName":"칼랑코에",
      "plantScientific":"Kalanchoe",
      "plantOrigin":"마다가스카르",
      "plantFamily":"돌나무과",
      "plantGroup":"씨앗주머니H",
      "plantLuminous":"음지",
      "plantWatering":"속 흙이 마르면 흠뻑 물주기",
      "plantPoint":80
   },
   {
      "plantNo":32,
      "plantName":"아이비",
      "plantScientific":"Hedera helix",
      "plantOrigin":"한국, 중국, 일본",
      "plantFamily":"두릅나무과",
      "plantGroup":"씨앗주머니H",
      "plantLuminous":"음지",
      "plantWatering":"1주일에 2번 씩 물주기",
      "plantPoint":80
   },
   {
      "plantNo":33,
      "plantName":"팔손이",
      "plantScientific":"Fatsia japonica",
      "plantOrigin":"한국, 일본, 동아시아",
      "plantFamily":"두릅나무과",
      "plantGroup":"씨앗주머니H",
      "plantLuminous":"음지",
      "plantWatering":"물이 마르지 않도록 관리",
      "plantPoint":80
   },
   {
      "plantNo":34,
      "plantName":"듀란타 (발렌타인 자스민)",
      "plantScientific":"Duranta repens",
      "plantOrigin":"브라질",
      "plantFamily":"마편초과",
      "plantGroup":"씨앗주머니A",
      "plantLuminous":"양지",
      "plantWatering":"1주일에 한 번씩 물주기",
      "plantPoint":20
   },
   {
      "plantNo":35,
      "plantName":"란타나",
      "plantScientific":"Lantana",
      "plantOrigin":"중남미지역",
      "plantFamily":"마편초과",
      "plantGroup":"씨앗주머니A",
      "plantLuminous":"양지",
      "plantWatering":"1주일에 한 번씩 1인치의 흙이 젖을 만큼 물주기",
      "plantPoint":20
   },
   {
      "plantNo":36,
      "plantName":"레몬버베나 (방취목)",
      "plantScientific":"Aloysia triphylla BRITT",
      "plantOrigin":"남아메리카",
      "plantFamily":"마편초과",
      "plantGroup":"씨앗주머니A",
      "plantLuminous":"양지",
      "plantWatering":"1주일에 한 번씩 물주기",
      "plantPoint":20
   },
   {
      "plantNo":37,
      "plantName":"오렌지자스민",
      "plantScientific":"Murraya paniculata",
      "plantOrigin":"마다가스카르, 말레이시아",
      "plantFamily":"물푸레나무과",
      "plantGroup":"씨앗주머니H",
      "plantLuminous":"양지",
      "plantWatering":"흙의 윗부분이 마를 때 물주기",
      "plantPoint":80
   },
   {
      "plantNo":38,
      "plantName":"은목서(만리향)",
      "plantScientific":"Pittosporum tobira",
      "plantOrigin":"한국, 중국",
      "plantFamily":"물푸레나무과",
      "plantGroup":"씨앗주머니H",
      "plantLuminous":"양지",
      "plantWatering":"5~7일 마다 흙이 마를 때 물주기",
      "plantPoint":80
   },
   {
      "plantNo":39,
      "plantName":"맥문동",
      "plantScientific":"Liriope muscari",
      "plantOrigin":"한국, 중국, 일본, 타이완",
      "plantFamily":"백합과",
      "plantGroup":"씨앗주머니C",
      "plantLuminous":"음지",
      "plantWatering":"(여름) 1달에 한 번씩 많은 물주기",
      "plantPoint":40
   },
   {
      "plantNo":40,
      "plantName":"알로에",
      "plantScientific":"Aloe",
      "plantOrigin":"아프리카",
      "plantFamily":"백합과",
      "plantGroup":"씨앗주머니C",
      "plantLuminous":"음지",
      "plantWatering":"여름엔 흙이 건조할 때 물주기, 겨울엔 거의 주지 않는다",
      "plantPoint":40
   },
   {
      "plantNo":41,
      "plantName":"애란 (소엽맥문동)",
      "plantScientific":"Ophiopogon japonicus",
      "plantOrigin":"한국, 일본",
      "plantFamily":"백합과",
      "plantGroup":"씨앗주머니C",
      "plantLuminous":"음지",
      "plantWatering":"마르지 않을 정도로만 물주기",
      "plantPoint":40
   },
   {
      "plantNo":42,
      "plantName":"엽란",
      "plantScientific":"Aspidistra elatior",
      "plantOrigin":"한국, 중국",
      "plantFamily":"백합과",
      "plantGroup":"씨앗주머니C",
      "plantLuminous":"음지",
      "plantWatering":"마르지 않을 정도로만 물주기",
      "plantPoint":40
   },
   {
      "plantNo":43,
      "plantName":"꽃베고니아",
      "plantScientific":"Begonia",
      "plantOrigin":"브라질",
      "plantFamily":"베고니아과",
      "plantGroup":"씨앗주머니E",
      "plantLuminous":"양지",
      "plantWatering":"마르지 않을 정도로만 물주기",
      "plantPoint":65
   },
   {
      "plantNo":44,
      "plantName":"안젤리카",
      "plantScientific":"Angelica",
      "plantOrigin":"알푸스",
      "plantFamily":"산형과",
      "plantGroup":"씨앗주머니A",
      "plantLuminous":"음지",
      "plantWatering":"흙이 마르지 않도록 물주기",
      "plantPoint":20
   },
   {
      "plantNo":45,
      "plantName":"회향(펜넬)",
      "plantScientific":"Foeniculum vulgare",
      "plantOrigin":"지중해",
      "plantFamily":"산형과",
      "plantGroup":"씨앗주머니A",
      "plantLuminous":"양지",
      "plantWatering":"1주일에 최소 1번 물주기",
      "plantPoint":20
   },
   {
      "plantNo":46,
      "plantName":"실버레이디",
      "plantScientific":"Blechnum gibbum",
      "plantOrigin":"호주",
      "plantFamily":"새깃아재비과",
      "plantGroup":"씨앗주머니F",
      "plantLuminous":"음지",
      "plantWatering":"(건기) 2일에 한 번씩 물주기",
      "plantPoint":70
   },
   {
      "plantNo":47,
      "plantName":"송엽국",
      "plantScientific":"Lampranthus spectabilis",
      "plantOrigin":"남아메리카",
      "plantFamily":"석류풀과",
      "plantGroup":"씨앗주머니G",
      "plantLuminous":"양지",
      "plantWatering":"자른 곳을 갈라 깊은 물에 담궈 관리",
      "plantPoint":85
   },
   {
      "plantNo":48,
      "plantName":"기둥선인장",
      "plantScientific":"Cereus",
      "plantOrigin":"멕시코",
      "plantFamily":"선인장과",
      "plantGroup":"씨앗주머니F",
      "plantLuminous":"양지",
      "plantWatering":"흙이 최소 3일 정도 말라 있으면 물주기",
      "plantPoint":70
   },
   {
      "plantNo":49,
      "plantName":"팬지",
      "plantScientific":"Viola tricolor",
      "plantOrigin":"유럽",
      "plantFamily":"제비꽃과",
      "plantGroup":"씨앗주머니L",
      "plantLuminous":"양지",
      "plantWatering":"흙 표면이 건조할 때 충분한 물주기",
      "plantPoint":100
   },
   {
      "plantNo":50,
      "plantName":"로즈제라늄",
      "plantScientific":"Pelargonium graveolens",
      "plantOrigin":"이집트",
      "plantFamily":"쥐손이풀과",
      "plantGroup":"씨앗주머니C",
      "plantLuminous":"양지",
      "plantWatering":"흙이 마르려고 할 때 한 번씩 물주기",
      "plantPoint":40
   },
   {
      "plantNo":51,
      "plantName":"애플사이다제라늄",
      "plantScientific":"Pelargonium hortorum",
      "plantOrigin":"남아프리카",
      "plantFamily":"쥐손이풀과",
      "plantGroup":"씨앗주머니C",
      "plantLuminous":"양지",
      "plantWatering":"흙이 마르려고 할 때 한 번씩 물주기",
      "plantPoint":40
   },
   {
      "plantNo":52,
      "plantName":"제라늄",
      "plantScientific":"Pelargonium",
      "plantOrigin":"남아프리카",
      "plantFamily":"쥐손이풀과",
      "plantGroup":"씨앗주머니C",
      "plantLuminous":"음지",
      "plantWatering":"겉흙이 건조해지기 전에 충분히 물주기",
      "plantPoint":40
   },
   {
      "plantNo":53,
      "plantName":"셀럼",
      "plantScientific":"Philodendron selloum",
      "plantOrigin":"브라질, 파라과이",
      "plantFamily":"천남성과",
      "plantGroup":"씨앗주머니E",
      "plantLuminous":"음지",
      "plantWatering":"1주일에 한 번 이상 물주기",
      "plantPoint":65
   },
   {
      "plantNo":54,
      "plantName":"알로카시아",
      "plantScientific":"Alocasia",
      "plantOrigin":"말레이시아",
      "plantFamily":"천남성과",
      "plantGroup":"씨앗주머니E",
      "plantLuminous":"양지",
      "plantWatering":"조금 건조하게 관리하고 과습에 주의",
      "plantPoint":65
   },
   {
      "plantNo":55,
      "plantName":"빌베르기아 누탄스",
      "plantScientific":"Billbergia nutans",
      "plantOrigin":"브라질, 우루과이, 파라과이, 아르헨티나",
      "plantFamily":"파인애플과",
      "plantGroup":"씨앗주머니G",
      "plantLuminous":"음지",
      "plantWatering":"여름에 정기적으로 물주고 겨울에는 여름보다 적게 준다.",
      "plantPoint":85
   },
   {
      "plantNo":56,
      "plantName":"틸란(pink quill)",
      "plantScientific":"Wallisia cyanea",
      "plantOrigin":"남아메리카",
      "plantFamily":"파인애플과",
      "plantGroup":"씨앗주머니G",
      "plantLuminous":"음지",
      "plantWatering":"주 2-3회 잎이 촉촉이 젖을 정도로 스프레이 해주기",
      "plantPoint":85
   },
   {
      "plantNo":57,
      "plantName":"여인초",
      "plantScientific":"Ravenala madagascariensis",
      "plantOrigin":"남아프리카",
      "plantFamily":"파초과",
      "plantGroup":"씨앗주머니F",
      "plantLuminous":"음지",
      "plantWatering":"겉흙이 건조해지기 전에 충분히 물주기",
      "plantPoint":70
   },
   {
      "plantNo":58,
      "plantName":"서향동백",
      "plantScientific":"Camellia japonica L.",
      "plantOrigin":"일본, 중국, 한국",
      "plantFamily":"동백나무과",
      "plantGroup":"씨앗주머니H",
      "plantLuminous":"음지",
      "plantWatering":"1, 2주에 한 번씩 14-18인치의 흙이 젖을 정도로 물주기",
      "plantPoint":80
   },
   {
      "plantNo":59,
      "plantName":"자색아카시아",
      "plantScientific":"Acacia carnei",
      "plantOrigin":"북아메리카",
      "plantFamily":"콩과",
      "plantGroup":"씨앗주머니D",
      "plantLuminous":"양지",
      "plantWatering":"더운 날씨에는 3-4주에 한 번씩 물주기",
      "plantPoint":60
   },

   {
      "plantNo":60,
      "plantName":"3조 : 풀떼기 키우기",
      "plantScientific":"강지원",
      "plantOrigin":"강청운",
      "plantFamily":"김주환",
      "plantGroup":"종효련",
      "plantLuminous":"도와준 사람 : 우리 쌤💖",
      "plantWatering":"더운 날씨에는 커피를",
      "plantPoint": 100000000
   }


]



function getPlantNo() {
   return plant.plantNo;
}